### PR TITLE
build: update angular deps to angular#master (@klingon/ui)

### LINKED ISSUE #55: switch to angular/master#HEAD
Let's use angular#master^HEAD as our main version.

NOTE: this is forcing us to stay up to date but also, this may introduce some breaking changes, so we should be reactive and fix bugs as they arise ^^

### PR DESCRIPTION
**Pull request by daniloff200**
closes  #55

### CODE REVIEW

**Comment by manekinekko** [comment]
LGTM. But we need to make sure that the current UI is still in sync with the latest version of angular/cli-builds#master. The CLI commands and flags are currently hardcoded in the UI :/

**Comment by daniloff200** [comment]
:D I didn't completely get, what u mean :D 

Can I assist u with that? @manekinekko

**Comment by manekinekko** [comment]
What I mean is that all the CLI flags are hard coded in the UI, ie. [build](https://github.com/angular-klingon/klingon/blob/master/packages/klingon-ui/src/app/cli/build/build.component.html), [server](https://github.com/angular-klingon/klingon/blob/master/packages/klingon-ui/src/app/cli/serve/serve.component.html), etc... So updating the CLI to master may break if the hard-coded CLI flags are no more in sync with the latest version.

This rises another issue which is: Hard coding the CLI commands and flags in the UI is not a good approach anymore!

Does that make sense?

**Comment by daniloff200** [comment]
I think, right it this PR also can be closed @manekinekko

**Comment by manekinekko** [comment]
Sorry about that @daniloff200 we had some issues with master on other projects. So we had to revert to fixed version.

**Pull request closed without merging**
